[parity]
chain = "/ethereum/genesis.json" 
base_path = "/ethereum/" 

[network]
port = 30304
reserved_peers=  "/ethereum/nodes" 
allow_ips = "all"

[rpc]
port = 8546
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces" ,"rpc", "parity_accounts"]
interface = "all"
cors = ["all"]

[account]
password = ["/ethereum/password"] 

[mining]
engine_signer = "0xff2149fb666865230bf7b818d06f485b0478b8a5"  
gas_floor_target = "40000000"

[misc]
logging = "own_tx=trace"
log_file = "/ethereum/log.log"
color = true
