[parity]
chain = "/ethereum/genesis.json" 
base_path = "/ethereum/" 

[network]
port = 30303
reserved_peers=  "/ethereum/nodes" 
allow_ips = "all"
# Override the bootnodes from selected chain file.
#bootnodes = ["enode://XXX@localhost:30300", "enode://XXXX@localhost:30301"]
# Enable or disable new peers discovery.
#discovery = false[rpc]

port = 8545
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces" ,"rpc", "parity_accounts"]
interface = "all"
cors = ["all"]

[account]
password = ["/ethereum/password"] 

[mining]
engine_signer = "0x9086299eceb892774004d1093bbdf26ddb3b6bd7"  
gas_floor_target = "40000000"

[misc]
logging = "own_tx=trace"
log_file = "/ethereum/log.log"
color = true
